using System;
using System.Collections.Generic;

public interface IReportBuilder
{
    void SetHeader(string header);
    void SetContent(string content);
    void SetFooter(string footer);
    void AddSection(string sectionName, string sectionContent);
    void SetStyle(ReportStyle style);
    Report GetReport();
}

public class ReportStyle
{
    public string BackgroundColor { get; set; }
    public string FontColor { get; set; }
    public int FontSize { get; set; }
}

public class Report
{
    public string Header { get; set; }
    public string Content { get; set; }
    public string Footer { get; set; }
    public List<string> Sections { get; set; } = new List<string>();
    public ReportStyle Style { get; set; }

    public void Export(string format)
    {
        if (format == "text")
        {
            Console.WriteLine($"Report in Text Format\n{Header}\n{Content}\n{Footer}");
            foreach (var section in Sections)
            {
                Console.WriteLine(section);
            }
        }
        else if (format == "html")
        {
            Console.WriteLine($"<html>\n<body style='background-color:{Style.BackgroundColor};color:{Style.FontColor};font-size:{Style.FontSize}px;'>");
            Console.WriteLine($"{Header}");
            Console.WriteLine($"{Content}");
            foreach (var section in Sections)
            {
                Console.WriteLine($"<section>{section}</section>");
            }
            Console.WriteLine($"{Footer}</body></html>");
        }
    }
}

public class TextReportBuilder : IReportBuilder
{
    private Report _report = new Report();

    public void SetHeader(string header)
    {
        _report.Header = header;
    }

    public void SetContent(string content)
    {
        _report.Content = content;
    }

    public void SetFooter(string footer)
    {
        _report.Footer = footer;
    }

    public void AddSection(string sectionName, string sectionContent)
    {
        _report.Sections.Add($"{sectionName}: {sectionContent}");
    }

    public void SetStyle(ReportStyle style)
    {
        _report.Style = style;
    }

    public Report GetReport()
    {
        return _report;
    }
}

public class HtmlReportBuilder : IReportBuilder
{
    private Report _report = new Report();

    public void SetHeader(string header)
    {
        _report.Header = $"<h1>{header}</h1>";
    }

    public void SetContent(string content)
    {
        _report.Content = $"<p>{content}</p>";
    }

    public void SetFooter(string footer)
    {
        _report.Footer = $"<footer>{footer}</footer>";
    }

    public void AddSection(string sectionName, string sectionContent)
    {
        _report.Sections.Add($"<h2>{sectionName}</h2><p>{sectionContent}</p>");
    }

    public void SetStyle(ReportStyle style)
    {
        _report.Style = style;
    }

    public Report GetReport()
    {
        return _report;
    }
}

public class ReportDirector
{
    public void ConstructReport(IReportBuilder builder, ReportStyle style)
    {
        builder.SetHeader("Monthly Report");
        builder.SetContent("This is the monthly performance report.");
        builder.SetFooter("Report generated by Company.");
        builder.AddSection("Sales", "Sales data for the month.");
        builder.SetStyle(style);
    }
}

public class Program
{
    static void Main(string[] args)
    {
        ReportDirector director = new ReportDirector();

        IReportBuilder textReportBuilder = new TextReportBuilder();
        ReportStyle textStyle = new ReportStyle { BackgroundColor = "white", FontColor = "black", FontSize = 12 };
        director.ConstructReport(textReportBuilder, textStyle);
        Report textReport = textReportBuilder.GetReport();
        textReport.Export("text");

        Console.WriteLine("\n---------------------------------------\n");

        IReportBuilder htmlReportBuilder = new HtmlReportBuilder();
        ReportStyle htmlStyle = new ReportStyle { BackgroundColor = "#f0f0f0", FontColor = "blue", FontSize = 14 };
        director.ConstructReport(htmlReportBuilder, htmlStyle);
        Report htmlReport = htmlReportBuilder.GetReport();
        htmlReport.Export("html");
    }
}
